Repository project-lyrics/api-server, pull requests merged in 2024-10, with the labels that each got.

#49 마이페이지 노트 조회 수정
  src/main/java/com/projectlyrics/server/domain/favoriteartist/api/FavoriteArtistController.java
  src/main/java/com/projectlyrics/server/domain/favoriteartist/repository/FavoriteArtistQueryRepository.java
  src/main/java/com/projectlyrics/server/domain/favoriteartist/repository/impl/QueryDslFavoriteArtistQueryRepository.java
  src/main/java/com/projectlyrics/server/domain/favoriteartist/service/FavoriteArtistQueryService.java
  src/main/java/com/projectlyrics/server/domain/note/api/NoteController.java
  src/main/java/com/projectlyrics/server/domain/note/repository/NoteQueryRepository.java
  src/main/java/com/projectlyrics/server/domain/note/repository/impl/QueryDslNoteQueryRepository.java
  src/main/java/com/projectlyrics/server/domain/note/service/NoteQueryService.java
  src/test/java/com/projectlyrics/server/domain/favoriteartist/api/FavoriteArtistControllerTest.java
  src/test/java/com/projectlyrics/server/domain/favoriteartist/service/FavoriteArtistQueryServiceTest.java
  src/test/java/com/projectlyrics/server/domain/note/api/NoteControllerTest.java
  src/test/java/com/projectlyrics/server/domain/note/service/NoteCommandServiceTest.java
  src/test/java/com/projectlyrics/server/domain/note/service/NoteQueryServiceTest.java
Labels: feat 🔥, ♻️ refactor

#51 Notification 응답에 created_at 필드 추가
  src/main/java/com/projectlyrics/server/domain/notification/api/dto/response/NotificationGetResponse.java
  src/main/java/com/projectlyrics/server/domain/notification/repository/impl/QueryDslNotificationQueryRepository.java
  src/test/java/com/projectlyrics/server/domain/notification/api/NotificationControllerTest.java
Labels: feat 🔥

#52 추가 기능 구현
  src/main/java/com/projectlyrics/server/domain/artist/api/ArtistController.java
  src/main/java/com/projectlyrics/server/domain/artist/repository/impl/QueryDslArtistQueryRepository.java
  src/main/java/com/projectlyrics/server/domain/artist/service/ArtistQueryService.java
  src/main/java/com/projectlyrics/server/domain/auth/service/AuthCommandService.java
  src/main/java/com/projectlyrics/server/domain/notification/domain/Notification.java
  src/main/java/com/projectlyrics/server/domain/notification/service/NotificationCommandService.java
  src/main/java/com/projectlyrics/server/domain/user/api/UserController.java
  src/main/java/com/projectlyrics/server/domain/user/dto/request/UserUpdateRequest.java
  src/main/java/com/projectlyrics/server/domain/user/dto/response/UserProfileResponse.java
  src/main/java/com/projectlyrics/server/domain/user/dto/response/UserUpdateResponse.java
  src/main/java/com/projectlyrics/server/domain/user/entity/TermsAgreements.java
  src/main/java/com/projectlyrics/server/domain/user/entity/User.java
  src/main/java/com/projectlyrics/server/domain/user/entity/UserCreate.java
  src/main/java/com/projectlyrics/server/domain/user/entity/Username.java
  src/main/java/com/projectlyrics/server/domain/user/repository/UserCommandRepository.java
  src/main/java/com/projectlyrics/server/domain/user/repository/UserQueryRepository.java
  src/main/java/com/projectlyrics/server/domain/user/repository/impl/QueryDslUserQueryRepository.java
  src/main/java/com/projectlyrics/server/domain/user/service/UserCommandService.java
  src/main/java/com/projectlyrics/server/domain/user/service/UserQueryService.java
  src/test/java/com/projectlyrics/server/domain/artist/service/ArtistQueryServiceIntegrationTest.java
  src/test/java/com/projectlyrics/server/domain/auth/service/AuthCommandServiceIntegrationTest.java
  src/test/java/com/projectlyrics/server/domain/user/api/UserControllerTest.java
  src/test/java/com/projectlyrics/server/domain/user/service/UserCommandServiceTest.java
  src/test/java/com/projectlyrics/server/domain/user/service/UserQueryServiceTest.java
  src/test/java/com/projectlyrics/server/support/ControllerTest.java
  src/test/java/com/projectlyrics/server/support/fixture/UserFixture.java
Labels: feat 🔥

#53 아티스트 정렬 기준 변경에 따른 테스트 수정
  src/main/java/com/projectlyrics/server/domain/artist/api/ArtistController.java
  src/test/java/com/projectlyrics/server/domain/artist/api/ArtistControllerTest.java
  src/test/java/com/projectlyrics/server/domain/artist/service/ArtistQueryServiceIntegrationTest.java
Labels: fix 🛠️

#50 조치 기능 개발
  src/main/java/com/projectlyrics/server/domain/auth/exception/ForcedWithdrawalUserException.java
  src/main/java/com/projectlyrics/server/domain/auth/service/AuthCommandService.java
  src/main/java/com/projectlyrics/server/domain/comment/service/CommentCommandService.java
  src/main/java/com/projectlyrics/server/domain/common/entity/BaseEntity.java
  src/main/java/com/projectlyrics/server/domain/common/entity/enumerate/EntityStatusEnum.java
  src/main/java/com/projectlyrics/server/domain/common/message/ErrorCode.java
  src/main/java/com/projectlyrics/server/domain/discipline/domain/Discipline.java
  src/main/java/com/projectlyrics/server/domain/discipline/domain/DisciplineCreate.java
  src/main/java/com/projectlyrics/server/domain/discipline/domain/DisciplineReason.java
  src/main/java/com/projectlyrics/server/domain/discipline/domain/DisciplineType.java
  src/main/java/com/projectlyrics/server/domain/discipline/dto/request/DisciplineCreateRequest.java
  src/main/java/com/projectlyrics/server/domain/discipline/exception/InvalidDisciplineActionException.java
  src/main/java/com/projectlyrics/server/domain/discipline/exception/InvalidDisciplineCreateException.java
  src/main/java/com/projectlyrics/server/domain/discipline/repository/DisciplineCommandRepository.java
  src/main/java/com/projectlyrics/server/domain/discipline/repository/DisciplineQueryRepository.java
  src/main/java/com/projectlyrics/server/domain/discipline/repository/impl/QueryDslDisciplineQueryRepository.java
  src/main/java/com/projectlyrics/server/domain/discipline/service/DisciplineCommandService.java
  src/main/java/com/projectlyrics/server/domain/like/repository/LikeQueryRepository.java
  src/main/java/com/projectlyrics/server/domain/like/repository/impl/QueryDslLikeQueryRepository.java
  src/main/java/com/projectlyrics/server/domain/note/service/NoteCommandService.java
  src/main/java/com/projectlyrics/server/domain/notification/domain/Notification.java
  src/main/java/com/projectlyrics/server/domain/notification/domain/NotificationType.java
  src/main/java/com/projectlyrics/server/domain/notification/domain/event/DisciplineEvent.java
  src/main/java/com/projectlyrics/server/domain/notification/service/NotificationCommandService.java
  src/main/java/com/projectlyrics/server/domain/report/dto/request/ReportCreateRequest.java
  src/main/java/com/projectlyrics/server/domain/report/service/ReportCommandService.java
  src/main/java/com/projectlyrics/server/domain/user/entity/User.java
  src/main/java/com/projectlyrics/server/domain/user/repository/UserQueryRepository.java
  src/main/java/com/projectlyrics/server/domain/user/repository/impl/QueryDslUserQueryRepository.java
  src/main/java/com/projectlyrics/server/global/slack/SlackClient.java
  src/main/java/com/projectlyrics/server/global/slack/api/SlackController.java
  src/test/java/com/projectlyrics/server/domain/auth/service/AuthCommandServiceIntegrationTest.java
  src/test/java/com/projectlyrics/server/domain/comment/service/CommentCommandServiceMockTest.java
  src/test/java/com/projectlyrics/server/domain/comment/service/CommentCommandServiceTest.java
  src/test/java/com/projectlyrics/server/domain/discipline/domain/DisciplineTest.java
  src/test/java/com/projectlyrics/server/domain/discipline/service/DisciplineCommandServiceTest.java
  src/test/java/com/projectlyrics/server/domain/note/service/NoteCommandServiceTest.java
  src/test/java/com/projectlyrics/server/domain/notification/service/NotificationCommandServiceTest.java
  src/test/java/com/projectlyrics/server/domain/report/service/ReportCommandServiceTest.java
  src/test/java/com/projectlyrics/server/support/ControllerTest.java
  src/test/java/com/projectlyrics/server/support/fixture/DisciplineFixture.java
  src/test/java/com/projectlyrics/server/support/fixture/ReportFixture.java
  src/test/resources/application.yml
Labels: feat 🔥
