Repository project-lyrics/api-server, pull requests merged in 2024-06, with the labels that each got.

#15 [SCRUM-103] refactor: 토큰 유효성 API 삭제
  src/main/java/com/projectlyrics/server/domain/auth/api/AuthController.java
  src/main/java/com/projectlyrics/server/domain/auth/api/AuthControllerSwagger.java
  src/main/java/com/projectlyrics/server/domain/auth/dto/response/UserTokenValidationResponse.java
  src/main/java/com/projectlyrics/server/domain/user/service/UserCommandService.java
  src/test/java/com/projectlyrics/server/domain/user/service/UserCommandServiceTest.java
Labels: ♻️ refactor

#18 [SCRUM-110] 테스트 코드 추가 및 전체적인 리팩터링
  .gitignore
  build.gradle
  src/main/java/com/projectlyrics/server/domain/artist/api/ArtistController.java
  src/main/java/com/projectlyrics/server/domain/artist/entity/Artist.java
  src/main/java/com/projectlyrics/server/domain/artist/repository/impl/QueryDslArtistQueryRepository.java
  src/main/java/com/projectlyrics/server/domain/artist/service/ArtistCommandService.java
  src/main/java/com/projectlyrics/server/domain/artist/service/ArtistQueryService.java
  src/main/java/com/projectlyrics/server/domain/auth/authentication/JwtAuthenticationEntryPoint.java
  src/main/java/com/projectlyrics/server/domain/auth/authentication/JwtAuthenticationFilter.java
  src/main/java/com/projectlyrics/server/domain/auth/entity/Auth.java
  src/main/java/com/projectlyrics/server/domain/auth/jwt/JwtTokenProvider.java
  src/main/java/com/projectlyrics/server/domain/auth/service/apple/AppleSocialService.java
  src/main/java/com/projectlyrics/server/domain/common/dto/util/CursorBasePaginatedResponse.java
  src/main/java/com/projectlyrics/server/domain/common/entity/BaseEntity.java
  src/main/java/com/projectlyrics/server/domain/record/api/RecordController.java
  src/main/java/com/projectlyrics/server/domain/record/domain/Record.java
  src/main/java/com/projectlyrics/server/domain/record/repository/impl/QueryDslRecordQueryRepository.java
  src/main/java/com/projectlyrics/server/domain/record/service/RecordCommandService.java
  src/main/java/com/projectlyrics/server/domain/record/service/RecordQueryService.java
  src/main/java/com/projectlyrics/server/domain/user/entity/User.java
  src/main/java/com/projectlyrics/server/domain/user/repository/impl/QueryDslUserQueryRepository.java
  src/main/java/com/projectlyrics/server/domain/user/service/UserCommandService.java
  src/main/java/com/projectlyrics/server/global/exception/FeelinException.java
  src/test/java/com/projectlyrics/server/common/ControllerTest.java
  src/test/java/com/projectlyrics/server/common/IntegrationTest.java
  src/test/java/com/projectlyrics/server/common/RepositoryTest.java
  src/test/java/com/projectlyrics/server/common/db/DatabaseCleaner.java
  src/test/java/com/projectlyrics/server/common/db/DatabaseCleanerExtension.java
  src/test/java/com/projectlyrics/server/common/fixture/ArtistFixture.java
  src/test/java/com/projectlyrics/server/common/fixture/RecordFixture.java
  src/test/java/com/projectlyrics/server/common/fixture/UserFixture.java
  src/test/java/com/projectlyrics/server/domain/artist/api/ArtistControllerTest.java
  src/test/java/com/projectlyrics/server/domain/artist/dto/request/ArtistAddRequestTest.java
  src/test/java/com/projectlyrics/server/domain/artist/repository/ArtistQueryRepositoryTest.java
  src/test/java/com/projectlyrics/server/domain/artist/service/ArtistCommandServiceIntegrationTest.java
  src/test/java/com/projectlyrics/server/domain/artist/service/ArtistCommandServiceTest.java
  src/test/java/com/projectlyrics/server/domain/artist/service/ArtistQueryServiceIntegrationTest.java
  src/test/java/com/projectlyrics/server/domain/artist/service/ArtistQueryServiceTest.java
  src/test/java/com/projectlyrics/server/domain/record/service/RecordCommandServiceTest.java
  src/test/java/com/projectlyrics/server/domain/record/service/RecordQueryServiceTest.java
  src/test/java/com/projectlyrics/server/domain/user/service/UserCommandServiceIntegrationTest.java
  src/test/java/com/projectlyrics/server/domain/user/service/UserCommandServiceTest.java
  src/test/java/com/projectlyrics/server/domain/user/service/UserQueryServiceTest.java
  src/test/java/com/projectlyrics/server/utils/UserTestUtil.java
  src/test/resources/application.yml
Labels: fix 🛠️, ♻️ refactor

#20 각 도메인에 테스트 추가 및 요구사항 맞춘 리팩토링
  src/main/java/com/projectlyrics/server/domain/artist/api/ArtistController.java
  src/main/java/com/projectlyrics/server/domain/artist/api/ArtistControllerSwagger.java
  src/main/java/com/projectlyrics/server/domain/artist/service/ArtistCommandService.java
  src/main/java/com/projectlyrics/server/domain/auth/api/AuthController.java
  src/main/java/com/projectlyrics/server/domain/auth/api/AuthControllerSwagger.java
  src/main/java/com/projectlyrics/server/domain/common/dto/SuccessResponse.java
  src/main/java/com/projectlyrics/server/domain/common/message/SuccessMessage.java
  src/test/java/com/projectlyrics/server/domain/artist/api/ArtistControllerTest.java
  src/test/java/com/projectlyrics/server/domain/artist/repository/ArtistQueryRepositoryTest.java
  src/test/java/com/projectlyrics/server/domain/user/service/UserCommandServiceTest.java
  src/test/java/com/projectlyrics/server/domain/user/service/UserQueryServiceTest.java
Labels: ♻️ refactor, 🧠 test

#22 예외 처리 및 에러 코드 리팩터링
  src/main/java/com/projectlyrics/server/domain/artist/exception/ArtistNotFoundException.java
  src/main/java/com/projectlyrics/server/domain/artist/service/ArtistCommandService.java
  src/main/java/com/projectlyrics/server/domain/artist/service/ArtistQueryService.java
  src/main/java/com/projectlyrics/server/domain/auth/authentication/JwtAuthenticationFilter.java
  src/main/java/com/projectlyrics/server/domain/auth/exception/AccessTokenExpiredException.java
  src/main/java/com/projectlyrics/server/domain/auth/exception/InvalidAdminKeyException.java
  src/main/java/com/projectlyrics/server/domain/auth/exception/InvalidPublicKeyException.java
  src/main/java/com/projectlyrics/server/domain/auth/exception/WrongTokenTypeException.java
  src/main/java/com/projectlyrics/server/domain/auth/service/AuthCommandService.java
  src/main/java/com/projectlyrics/server/domain/auth/service/social/apple/AppleSocialService.java
  src/main/java/com/projectlyrics/server/domain/common/message/ErrorCode.java
  src/main/java/com/projectlyrics/server/domain/record/exception/RecordNotFoundException.java
  src/main/java/com/projectlyrics/server/domain/record/service/RecordQueryService.java
  src/main/java/com/projectlyrics/server/domain/user/exception/UserNotFoundException.java
  src/main/java/com/projectlyrics/server/domain/user/service/UserQueryService.java
  src/main/java/com/projectlyrics/server/global/exception/AuthException.java
  src/main/java/com/projectlyrics/server/global/exception/JwtValidationException.java
  src/main/java/com/projectlyrics/server/global/exception/NotFoundException.java
  src/main/java/com/projectlyrics/server/global/handler/FilterExceptionHandler.java
  src/main/java/com/projectlyrics/server/global/handler/GlobalExceptionHandler.java
  src/test/java/com/projectlyrics/server/domain/artist/service/ArtistCommandServiceIntegrationTest.java
  src/test/java/com/projectlyrics/server/domain/record/service/RecordQueryServiceTest.java
  src/test/java/com/projectlyrics/server/domain/user/service/UserQueryServiceTest.java
Labels: ♻️ refactor

#23 요구사항 반영 리팩토링
  build.gradle
  checkstyle.xml
  src/main/java/com/projectlyrics/server/domain/artist/dto/request/ArtistAddRequest.java
  src/main/java/com/projectlyrics/server/domain/artist/entity/Artist.java
  src/main/java/com/projectlyrics/server/domain/artist/service/ArtistCommandService.java
  src/main/java/com/projectlyrics/server/domain/auth/authentication/JwtAuthenticationFilter.java
  src/main/java/com/projectlyrics/server/domain/auth/authentication/UndefinedAccessHandler.java
  src/main/java/com/projectlyrics/server/domain/auth/dto/request/AuthUserLoginRequest.java
  src/main/java/com/projectlyrics/server/domain/auth/entity/Auth.java
  src/main/java/com/projectlyrics/server/domain/auth/exception/InvalidTokenException.java
  src/main/java/com/projectlyrics/server/domain/auth/exception/TokenExpiredException.java
  src/main/java/com/projectlyrics/server/domain/auth/service/AuthCommandService.java
  src/main/java/com/projectlyrics/server/domain/auth/service/dto/AuthSocialInfo.java
  src/main/java/com/projectlyrics/server/domain/auth/service/social/kakao/dto/KakaoUserInfoResponse.java
  src/main/java/com/projectlyrics/server/domain/common/message/ErrorCode.java
  src/main/java/com/projectlyrics/server/domain/common/util/DomainUtils.java
  src/main/java/com/projectlyrics/server/domain/user/entity/User.java
  src/main/java/com/projectlyrics/server/global/configuration/SecurityConfig.java
  src/main/java/com/projectlyrics/server/global/exception/DomainEmptyException.java
  src/main/java/com/projectlyrics/server/global/exception/DomainInvalidUrlException.java
  src/main/java/com/projectlyrics/server/global/exception/DomainNullFieldException.java
  src/test/java/com/projectlyrics/server/common/fixture/ArtistFixture.java
  src/test/java/com/projectlyrics/server/common/fixture/UserFixture.java
  src/test/java/com/projectlyrics/server/domain/common/util/DomainUtilsTest.java
Labels: ♻️ refactor

#24 온보딩 관련 기능 추가
  .github/workflows/CI-CD.yml
  .github/workflows/Test.yml
  .gitignore
  src/main/java/com/projectlyrics/server/domain/auth/api/AuthController.java
  src/main/java/com/projectlyrics/server/domain/auth/api/AuthControllerSwagger.java
  src/main/java/com/projectlyrics/server/domain/auth/authentication/JwtAuthenticationFilter.java
  src/main/java/com/projectlyrics/server/domain/auth/dto/request/AuthSignInRequest.java
  src/main/java/com/projectlyrics/server/domain/auth/dto/request/AuthSignUpRequest.java
  src/main/java/com/projectlyrics/server/domain/auth/dto/response/AuthLoginResponse.java
  src/main/java/com/projectlyrics/server/domain/auth/dto/response/AuthTokenResponse.java
  src/main/java/com/projectlyrics/server/domain/auth/exception/NotAgreeToTermsException.java
  src/main/java/com/projectlyrics/server/domain/auth/service/AuthCommandService.java
  src/main/java/com/projectlyrics/server/domain/auth/service/social/SocialServiceFactory.java
  src/main/java/com/projectlyrics/server/domain/auth/service/social/apple/AppleSocialService.java
  src/main/java/com/projectlyrics/server/domain/auth/service/social/kakao/KakaoSocialService.java
  src/main/java/com/projectlyrics/server/domain/common/message/ErrorCode.java
  src/main/java/com/projectlyrics/server/domain/common/util/DomainUtils.java
  src/main/java/com/projectlyrics/server/domain/user/entity/Gender.java
  src/main/java/com/projectlyrics/server/domain/user/entity/TermsAgreements.java
  src/main/java/com/projectlyrics/server/domain/user/entity/User.java
  src/main/java/com/projectlyrics/server/domain/user/entity/UserMetaInfo.java
  src/main/java/com/projectlyrics/server/domain/user/entity/Username.java
  src/main/java/com/projectlyrics/server/domain/user/exception/InvalidAgeException.java
  src/main/java/com/projectlyrics/server/domain/user/exception/InvalidUsernameException.java
  src/main/java/com/projectlyrics/server/domain/user/service/UserQueryService.java
  src/main/java/com/projectlyrics/server/global/configuration/SecurityConfig.java
  src/main/java/com/projectlyrics/server/global/handler/FilterExceptionHandler.java
  src/main/java/com/projectlyrics/server/global/handler/GlobalExceptionHandler.java
  src/main/resources/application.yml
  src/test/java/com/projectlyrics/server/common/ControllerTest.java
  src/test/java/com/projectlyrics/server/common/fixture/UserFixture.java
  src/test/java/com/projectlyrics/server/domain/artist/api/ArtistControllerTest.java
  src/test/java/com/projectlyrics/server/domain/artist/service/ArtistCommandServiceTest.java
  src/test/java/com/projectlyrics/server/domain/auth/api/AuthControllerTest.java
  src/test/java/com/projectlyrics/server/domain/auth/service/AuthCommandServiceIntegrationTest.java
  src/test/java/com/projectlyrics/server/domain/auth/service/AuthQueryServiceTest.java
  src/test/java/com/projectlyrics/server/domain/common/util/DomainUtilsTest.java
  src/test/java/com/projectlyrics/server/domain/user/entity/UserTest.java
  src/test/java/com/projectlyrics/server/domain/user/service/UserCommandServiceTest.java
  src/test/java/com/projectlyrics/server/domain/user/service/UserQueryServiceTest.java
  src/test/resources/application.yml
Labels: fix 🛠️, feat 🔥, ♻️ refactor
