Repository project-lyrics/api-server, pull requests merged in 2024-07, with the labels that each got.

#25 회원가입 약관 동의 api 수정 및 온보딩 관심 아티스트 등록 api 추가
  src/main/java/com/projectlyrics/server/domain/artist/api/ArtistController.java
  src/main/java/com/projectlyrics/server/domain/artist/dto/request/ArtistAddRequest.java
  src/main/java/com/projectlyrics/server/domain/artist/dto/request/ArtistUpdateRequest.java
  src/main/java/com/projectlyrics/server/domain/artist/dto/response/ArtistGetResponse.java
  src/main/java/com/projectlyrics/server/domain/artist/dto/response/ArtistUpdateResponse.java
  src/main/java/com/projectlyrics/server/domain/artist/entity/Artist.java
  src/main/java/com/projectlyrics/server/domain/artist/repository/ArtistQueryRepository.java
  src/main/java/com/projectlyrics/server/domain/artist/repository/impl/QueryDslArtistQueryRepository.java
  src/main/java/com/projectlyrics/server/domain/artist/service/ArtistCommandService.java
  src/main/java/com/projectlyrics/server/domain/artist/service/ArtistQueryService.java
  src/main/java/com/projectlyrics/server/domain/auth/authentication/JwtAuthenticationFilter.java
  src/main/java/com/projectlyrics/server/domain/auth/dto/request/AuthSignUpRequest.java
  src/main/java/com/projectlyrics/server/domain/auth/jwt/JwtTokenProvider.java
  src/main/java/com/projectlyrics/server/domain/common/dto/util/CursorBasePaginatedResponse.java
  src/main/java/com/projectlyrics/server/domain/common/util/QueryDslUtils.java
  src/main/java/com/projectlyrics/server/domain/favoriteartist/api/FavoriteArtistController.java
  src/main/java/com/projectlyrics/server/domain/favoriteartist/dto/request/CreateFavoriteArtistListRequest.java
  src/main/java/com/projectlyrics/server/domain/favoriteartist/entity/FavoriteArtist.java
  src/main/java/com/projectlyrics/server/domain/favoriteartist/repository/FavoriteArtistCommandRepository.java
  src/main/java/com/projectlyrics/server/domain/favoriteartist/repository/FavoriteArtistQueryRepository.java
  src/main/java/com/projectlyrics/server/domain/favoriteartist/repository/impl/QueryDslFavoriteArtistQueryRepository.java
  src/main/java/com/projectlyrics/server/domain/favoriteartist/service/FavoriteArtistCommandService.java
  src/main/java/com/projectlyrics/server/domain/record/dto/request/RecordGetResponse.java
  src/main/java/com/projectlyrics/server/domain/user/entity/TermsAgreements.java
  src/main/java/com/projectlyrics/server/domain/user/entity/User.java
  src/main/java/com/projectlyrics/server/global/dev/DummyDataInitializer.java
  src/main/java/com/projectlyrics/server/global/handler/GlobalExceptionHandler.java
  src/test/java/com/projectlyrics/server/common/ControllerTest.java
  src/test/java/com/projectlyrics/server/common/fixture/ArtistFixture.java
  src/test/java/com/projectlyrics/server/common/fixture/UserFixture.java
  src/test/java/com/projectlyrics/server/domain/artist/api/ArtistControllerTest.java
  src/test/java/com/projectlyrics/server/domain/artist/dto/request/ArtistAddRequestTest.java
  src/test/java/com/projectlyrics/server/domain/artist/service/ArtistCommandServiceIntegrationTest.java
  src/test/java/com/projectlyrics/server/domain/artist/service/ArtistCommandServiceTest.java
  src/test/java/com/projectlyrics/server/domain/artist/service/ArtistQueryServiceTest.java
  src/test/java/com/projectlyrics/server/domain/auth/api/AuthControllerTest.java
  src/test/java/com/projectlyrics/server/domain/auth/service/AuthCommandServiceIntegrationTest.java
  src/test/java/com/projectlyrics/server/domain/favoriteartist/api/FavoriteArtistControllerTest.java
  src/test/java/com/projectlyrics/server/domain/favoriteartist/service/FavoriteArtistCommandServiceTest.java
  src/test/java/com/projectlyrics/server/domain/user/entity/UserTest.java
  src/test/resources/application.yml
Labels: fix 🛠️, feat 🔥, ♻️ refactor

#26 유저 데이터 이메일 제거 리팩터링
  src/main/java/com/projectlyrics/server/domain/auth/service/dto/AuthSocialInfo.java
  src/main/java/com/projectlyrics/server/domain/auth/service/social/apple/dto/AppleUserInfoResponse.java
  src/main/java/com/projectlyrics/server/domain/auth/service/social/kakao/dto/KakaoAccount.java
  src/main/java/com/projectlyrics/server/domain/auth/service/social/kakao/dto/KakaoUserInfoResponse.java
  src/main/java/com/projectlyrics/server/domain/user/entity/User.java
  src/main/java/com/projectlyrics/server/global/dev/DummyDataInitializer.java
  src/test/java/com/projectlyrics/server/common/fixture/UserFixture.java
  src/test/java/com/projectlyrics/server/domain/auth/service/AuthCommandServiceIntegrationTest.java
  src/test/java/com/projectlyrics/server/domain/auth/service/AuthQueryServiceTest.java
  src/test/java/com/projectlyrics/server/domain/user/entity/UserTest.java
Labels: ♻️ refactor

#27 스웨거 문서 수정
  src/main/java/com/projectlyrics/server/domain/artist/dto/request/ArtistAddRequest.java
  src/main/java/com/projectlyrics/server/domain/artist/dto/request/ArtistUpdateRequest.java
  src/main/java/com/projectlyrics/server/domain/auth/api/AuthController.java
  src/main/java/com/projectlyrics/server/domain/auth/api/AuthControllerSwagger.java
  src/main/java/com/projectlyrics/server/domain/auth/authentication/UndefinedAccessHandler.java
  src/main/java/com/projectlyrics/server/domain/auth/dto/request/AuthSignUpRequest.java
  src/main/java/com/projectlyrics/server/domain/common/dto/ErrorResponse.java
  src/main/java/com/projectlyrics/server/domain/common/message/ErrorCode.java
  src/main/java/com/projectlyrics/server/domain/user/entity/User.java
  src/main/java/com/projectlyrics/server/domain/user/entity/Username.java
  src/main/java/com/projectlyrics/server/global/handler/GlobalExceptionHandler.java
  src/test/java/com/projectlyrics/server/common/fixture/UserFixture.java
  src/test/java/com/projectlyrics/server/domain/auth/api/AuthControllerTest.java
  src/test/java/com/projectlyrics/server/domain/auth/service/AuthCommandServiceIntegrationTest.java
  src/test/java/com/projectlyrics/server/domain/user/entity/UserTest.java
Labels: 📓 docs

#29 온보딩 API 및 스웨거 수정
  src/main/java/com/projectlyrics/server/domain/artist/api/ArtistController.java
  src/main/java/com/projectlyrics/server/domain/auth/dto/request/AuthSignInRequest.java
  src/main/java/com/projectlyrics/server/domain/auth/dto/request/AuthSignUpRequest.java
  src/main/java/com/projectlyrics/server/domain/auth/entity/Auth.java
  src/main/java/com/projectlyrics/server/domain/auth/entity/enumerate/AuthProvider.java
  src/main/java/com/projectlyrics/server/domain/auth/entity/enumerate/Role.java
  src/main/java/com/projectlyrics/server/domain/auth/exception/AlreadyExistsUserException.java
  src/main/java/com/projectlyrics/server/domain/auth/service/AuthCommandService.java
  src/main/java/com/projectlyrics/server/domain/auth/service/AuthQueryService.java
  src/main/java/com/projectlyrics/server/domain/auth/service/dto/AuthSocialInfo.java
  src/main/java/com/projectlyrics/server/domain/auth/service/social/SocialService.java
  src/main/java/com/projectlyrics/server/domain/auth/service/social/SocialServiceFactory.java
  src/main/java/com/projectlyrics/server/domain/auth/service/social/apple/AppleSocialService.java
  src/main/java/com/projectlyrics/server/domain/auth/service/social/apple/dto/AppleUserInfoResponse.java
  src/main/java/com/projectlyrics/server/domain/auth/service/social/kakao/KakaoSocialService.java
  src/main/java/com/projectlyrics/server/domain/auth/service/social/kakao/dto/KakaoUserInfoResponse.java
  src/main/java/com/projectlyrics/server/domain/common/message/ErrorCode.java
  src/main/java/com/projectlyrics/server/domain/user/entity/AuthProvider.java
  src/main/java/com/projectlyrics/server/domain/user/entity/ProfileCharacter.java
  src/main/java/com/projectlyrics/server/domain/user/entity/Role.java
  src/main/java/com/projectlyrics/server/domain/user/entity/SocialInfo.java
  src/main/java/com/projectlyrics/server/domain/user/entity/User.java
  src/main/java/com/projectlyrics/server/domain/user/repository/UserQueryRepository.java
  src/main/java/com/projectlyrics/server/domain/user/repository/impl/QueryDslUserQueryRepository.java
  src/main/java/com/projectlyrics/server/domain/user/service/UserQueryService.java
  src/main/java/com/projectlyrics/server/global/dev/DummyDataInitializer.java
  src/test/java/com/projectlyrics/server/domain/artist/api/ArtistControllerTest.java
  src/test/java/com/projectlyrics/server/domain/artist/service/ArtistQueryServiceIntegrationTest.java
  src/test/java/com/projectlyrics/server/domain/auth/api/AuthControllerTest.java
  src/test/java/com/projectlyrics/server/domain/auth/service/AuthCommandServiceIntegrationTest.java
  src/test/java/com/projectlyrics/server/domain/auth/service/AuthQueryServiceTest.java
  src/test/java/com/projectlyrics/server/domain/user/entity/UserTest.java
  src/test/java/com/projectlyrics/server/domain/user/service/UserQueryServiceTest.java
  src/test/java/com/projectlyrics/server/support/fixture/ArtistFixture.java
  src/test/java/com/projectlyrics/server/support/fixture/BaseFixture.java
  src/test/java/com/projectlyrics/server/support/fixture/UserFixture.java
Labels: fix 🛠️, ♻️ refactor, 📓 docs

#30 관심 아티스트 중복 추가 버그 수정 및 조회 기능 추가
  src/main/java/com/projectlyrics/server/domain/auth/authentication/jwt/JwtExtractor.java
  src/main/java/com/projectlyrics/server/domain/favoriteartist/repository/FavoriteArtistQueryRepository.java
  src/main/java/com/projectlyrics/server/domain/favoriteartist/repository/impl/QueryDslFavoriteArtistQueryRepository.java
  src/main/java/com/projectlyrics/server/domain/favoriteartist/service/FavoriteArtistCommandService.java
  src/main/java/com/projectlyrics/server/global/configuration/ClockConfig.java
Labels: fix 🛠️, feat 🔥

#31 관심 아티스트 조회 기능 추가
  src/main/java/com/projectlyrics/server/domain/favoriteartist/api/FavoriteArtistController.java
  src/main/java/com/projectlyrics/server/domain/favoriteartist/dto/FavoriteArtistResponse.java
  src/main/java/com/projectlyrics/server/domain/favoriteartist/entity/FavoriteArtist.java
  src/main/java/com/projectlyrics/server/domain/favoriteartist/service/FavoriteArtistQueryService.java
  src/main/java/com/projectlyrics/server/domain/user/entity/User.java
  src/test/java/com/projectlyrics/server/domain/favoriteartist/api/FavoriteArtistControllerTest.java
  src/test/java/com/projectlyrics/server/support/ControllerTest.java
  src/test/java/com/projectlyrics/server/support/fixture/FavoriteArtistFixture.java
  src/test/java/com/projectlyrics/server/support/fixture/UserFixture.java
Labels: feat 🔥

#33 토큰 검증 API 응답 body 추가
  src/main/java/com/projectlyrics/server/domain/auth/api/AuthController.java
  src/main/java/com/projectlyrics/server/domain/auth/dto/response/TokenValidateResponse.java
  src/test/java/com/projectlyrics/server/domain/auth/api/AuthControllerTest.java
Labels: ♻️ refactor
